# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('passwd', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sex', models.CharField(choices=[('0', '\u5973'), ('1', '\u7537')], max_length=4)),
                ('mobile', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('addr', models.CharField(max_length=256)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_reg_login.Family')),
            ],
        ),
    ]
