# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_reg_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
